[package]
name = "GLBTC"
version = "1.0.0"
authors = []

[addresses]
GLbtc="0x4080ecaccec584280809ff8bbeb5948735f250e6159f68ca762268d7fd322475"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
