[package]
name = "GBTC"
version = "1.0.0"
authors = []

[addresses]
Gbtc="0xbd4f4d25b0410220516389f153071949232993af1ca43a9257c936cf60448255"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
